name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: README
      run: | # make sure to enable Settings -> Actions -> General -> Workflow permissions -> Read and write permissions
        dotnet run --project ./AofC_2023/AofC_2023.fsproj -- generate_readme
        git config --global user.email "jonas.beckeman@gmail.com"
        git config --global user.name "GitHub Action"
        git commit README.md -m 'Re-build README.md' || echo "No changes to commit"
        git push origin || echo "No changes to commit"
    - name: Merge to main (if develop)
      if: contains(github.ref, 'develop')
      run: |
        git fetch --unshallow
        git checkout main
        git pull
        git merge --no-ff develop -m "Auto-merge develop to main"
        git push
