name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: README
      run: |        
        dotnet run --project ./AofC_2022/AofC_2022.fsproj -- generate_readme
        git config --global user.email "jonas.beckeman@gmail.com"
        git config --global user.name "GitHub Action"
        git commit README.md -m 'Re-build README.md' || echo "No changes to commit"
        git push origin || echo "No changes to commit"
